cinefrights/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("films/", include("films.urls"), name="films-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("movies.urls"), name="movies-urls"),
]

films/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.FilmsPageView.as_view(), name='films'),
    path('newsletter/', views.MembersView, name='news_letter'),
    path('unsubscribe/', views.Remove, name='unsubscribe'),
]

movies/urls.py
'''Imports'''
from . import views
from django.urls import path

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('recommend/', views.recommend_view, name='recommend'),
    path('<slug:slug>/', views.MovieDetailView, name='movie_detail'),
    path(
        '<slug:slug>/edit_comment/<int:comment_id>',
        views.comment_edit,
        name='comment_edit'
    ),
    path(
        '<slug:slug>/delete_comment/<int:comment_id>',
        views.comment_delete,
        name='comment_delete'
    ),
]

movies/models.py
'''Imports'''
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

POST_STATUS = ((0, "Not Published"), (1, "Published"))


class Movie(models.Model):
    """
    Class for movie posts.
    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="movie_posts")
    movie_poster = CloudinaryField('image', default='placeholder')
    release_date = models.SlugField(
        blank=False, null=False, default=0, max_length=4)
    summary = models.TextField(blank=False, null=False, default="text")
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=POST_STATUS, default=0)
    updated_on = models.DateTimeField(auto_now=True)
    excerpt = models.TextField(blank=True)
    imdb_rating = models.TextField(
        blank=False, null=False, max_length=3, default="0")
    rotten_tomatoes_rating = models.TextField(
        blank=False, null=False, max_length=3, default="0")
    our_rating = models.TextField(
        blank=False, null=False,  max_length=26, default="0")

    class Meta:
        '''
        A meta class for meta data, posts are listed from newest to oldest
        '''
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    """
    Class for user comments comment on a movie post.
    """
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, related_name="movie_comments")
    username = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="movie_comments")
    content = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        '''
        A meta class for meta data, comments are listed from newest to oldest
        '''
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.content} | by {self.username}"


class RecommendMovie(models.Model):
    """
    Class representing movie recommendation from user.
    """
    username = models.CharField(max_length=200)
    email = models.EmailField()
    movie_title = models.TextField(max_length=200)
    additional_comments = models.TextField(max_length=200)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"Movie recommendation from {self.username}"

movies/forms.py
from django import forms
from .models import Comment, RecommendMovie


class CommentForm(forms.ModelForm):
    """
    Movie comment field
    """
    class Meta:
        model = Comment
        fields = ('content',)


class RecommendMovieForm(forms.ModelForm):
    """
    Recommend a movie field
    """
    class Meta:
        model = RecommendMovie
        fields = ('username', 'email', 'movie_title', 'additional_comments')

movies/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Movie, Comment, RecommendMovie
from .forms import CommentForm, RecommendMovieForm


class HomePageView(generic.ListView):
    """
    View to display all movie posts on the homepage.
    """
    queryset = Movie.objects.filter(status=1)
    template_name = "movies/index.html"


def MovieDetailView(request, slug):
    """
    View to display selected movie post details.
    """
    queryset = Movie.objects.filter(status=1)
    movie = get_object_or_404(queryset, slug=slug)
    comments = movie.movie_comments.all().order_by("-created_on")
    comment_count = movie.movie_comments.filter(approved=True).count()
    movie.movie_comments.filter(approved=True).count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.username = request.user
            comment.movie = movie
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                """Your comment is successfully submitted,
                 it will appear after approval."""
            )
        else:
            messages.add_message(
                request, messages.ERROR,
                'Something went wrong, please try again.'
            )

    comment_form = CommentForm()

    return render(
        request,
        "movies/movie_detail.html",
        {
            "movie": movie,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
        },
    )


def recommend_view(request):
    """
    View to display recommend movie form.
    """

    if request.method == "POST":
        recommend_movie_form = RecommendMovieForm(data=request.POST)
        if recommend_movie_form.is_valid():
            recommend_movie_form.save()
            messages.add_message(
                request, messages.SUCCESS,
                """Thank you,we recieved your recommendation.
                You will get an respond within a week."""
            )
        else:
            messages.add_message(
                request, messages.ERROR,
                """Something went wrong, please try again."""
            )

    recommend_movie_form = RecommendMovieForm()

    return render(
        request,
        "movies/recommend_movie.html",
        {
            "recommend_movie_form": recommend_movie_form
        },
    )


def comment_edit(request, slug, comment_id):
    """
    View to edit movie comments.
    """
    if request.method == "POST":

        queryset = Movie.objects.filter(status=1)
        movie = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.username == request.user:
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.approved = False
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Your comment is updated.'
            )
        else:
            messages.add_message(
                request, messages.ERROR,
                'An error occured while updating comment, try again.'
            )

    return HttpResponseRedirect(reverse('movie_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    View to delete movie comments.
    """
    queryset = Movie.objects.filter(status=1)
    movie = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.username == request.user:
        comment.delete()
        messages.add_message(
            request, messages.SUCCESS, 'Comment deleted.'
        )
    else:
        messages.add_message(
            request, messages.ERROR,
            'You can only delete your own comments.'
        )

    return HttpResponseRedirect(reverse('movie_detail', args=[slug]))

movies/templates/movies/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- index.html content starts here -->
<div class="d-flex justify-content-center">
    <!-- Movie carousel -->
    <div class="row p-2">
        <div id="carousel-movies" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                {% for movie in movie_list|slice:":4" %}
                    <button type="button" data-bs-target="#carousel-movies" data-bs-slide-to="{{ forloop.counter0 }}" 
                    {% if forloop.first %}class="active" aria-current="true"{% endif %} aria-label="Slide {{ forloop.counter }}"></button>
                {% endfor %}
            </div>
            <div class="carousel-inner" >
                {% for movie in movie_list|slice:":4" %}
                    {% if  forloop.counter == 1 %}
                        <div class="carousel-item active" data-bs-interval="2000">
                        {% if "placeholder" in movie.movie_poster.url %}
                            <img src="{% static 'images/default-image.jpg' %}" class="d-block w-100" alt="{{movie.title}}">
                        {% else %}
                            <img class="d-block w-100" src="{{ movie.movie_poster.url }}" alt="{{movie.title}}">
                        {% endif %}
                        <div class="carousel-caption d-none d-md-block">
                            <a href="{% url 'movie_detail' movie.slug %}" class="carousel-caption"><h5 class="carousel-title">{{ movie.title }}</h5></a>
                            <p>{{ movie.excerpt }}</p>
                        </div>
                        </div>
                    {% else %}
                        <div class="carousel-item">
                        {% if "placeholder" in movie.movie_poster.url %}
                            <img src="{% static 'images/default-image.jpg' %}" class="d-block w-100" alt="{{ movie.title }}">
                        {% else %}
                            <img class="d-block w-100" src="{{ movie.movie_poster.url }}" alt="{{movie.title}}">
                        {% endif %}
                            <div class="carousel-caption d-none d-md-block">
                                <a href="{% url 'movie_detail' movie.slug %}" class="carousel-caption"><h5 class="carousel-title">{{ movie.title }}</h5></a>
                                <p>{{ movie.excerpt }}</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}  
            </div>
        </div>
    </div>
    <button class="carousel-control-prev d-none" type="button" data-bs-target="#carousel-movies" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next d-none" type="button" data-bs-target="#carousel-movies" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<!-- index.html content ends here -->
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}

<!-- movie_detail.html content starts here -->
<div class="container wrapper">
  <div class="row gx-5">
    <div class="col-sm-6 col-lg-6">
        <!-- The movie post title and ratings -->
        <div class="post-details">
          <h1 class="post-title movie-title">{{ movie.title }}</h1>
          <h2 class="post-subtitle h5 movie-title">Our Rating |
            {{ movie.our_rating }}</h2>
            <p class="post-subtitle movie-title">Imdb |
              {{ movie.imdb_rating }}</p>
            <p class="post-subtitle movie-title">Rotten Tomatoes |
              {{ movie.rotten_tomatoes_rating }}</p>
            <p class="post-subtitle movie-title">Release Date |
              {{ movie.release_date }}</p>
        </div>
          <!-- The movie post summary -->
          <div class="card-body p-3 detail-card">
            <p class="card-text"> {{ movie.summary | safe }}
            </p>
          </div>
        <!-- Displaying Comments -->
        <div class="card mb-4  mt-3">
          <h3>Comments: {{ comment_count }}</h3>
          <div class="card-body detail-card">
            <!-- for loop to iterate through each comment in comments -->
            {% for comment in comments %}
            <div
              class="p-2 comments{% if not comment.approved and comment.username == user %} faded{% elif not comment.approved %} d-none{% endif %}">
              <p class="font-weight-bold">
                {{ comment.username }}
                <span class="font-weight-normal">
                  {{ comment.created_on }}
                </span> wrote:
              </p>
              <div id="comment{{ comment.id }}">
                {{ comment.content | linebreaks }}
              </div>
              {% if not comment.approved and comment.username == user %}
              <p class="approval">This comment is awaiting approval</p>
              {% endif %}
              {% if user.is_authenticated and comment.username == user %}
              <button class="btn btn-edit" data-comment_id="{{ comment.id }}">Edit</button>
              <button class="btn btn-delete" data-comment_id="{{ comment.id }}">Delete</button>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          <!-- To create new comments -->
          <div class="card mb-3  mt-3 ">
            <div class="card-body detail-card">
              {% if user.is_authenticated %}
              <h3>Leave a comment:</h3>
              <p>Posting as: {{ user.username }}</p>
              <form id="commentForm" method="post" style="margin-top: 1.3em;">
                {{ comment_form | crispy }}
                {% csrf_token %}
                <button id="submitButton" type="submit" class="btn btn-signup btn-lg">Submit</button>
              </form>
              {% else %}
              <p>Log in to leave a comment</p>
              {% endif %}
            </div>
          </div>
        </div>
    </div>
    <!-- The movie post poster -->
    <div class="d-none d-md-block col-md-6 col-lg-6">
      {% if "placeholder" in movie.movie_poster.url %}
      <img class="img-fluid w-100" src="{% static 'images/default-image.jpg' %}" alt="placeholder image">
      {% else %}
      <img class="img-fluid w-100" src=" {{ movie.movie_poster.url }}" alt="{{ movie.title }}">
      {% endif %}
    </div>
  </div>
</div>
<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

movies/templates/movies/recommend_movie.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<!-- recommend_movie.html content starts here -->
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 my-5">
            <!-- Movie recommendation info -->
            <h2>Do you have a movie that you want to recommend to us to be featured?</h2>
            <p class="recommend">Fill out the below form and we will consider your request.</p>

            <!-- Movie recommendation form -->
            <form method="post">
                {{ recommend_movie_form | crispy }}
                {% csrf_token %}
                <button class="btn btn-secondary" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}